### PR TITLE
Docs fixes

### LINKED ISSUE #191: Docs: reference to official examples
Docs: reference to that: https://github.com/playwright-community/playwright-jest-examples

### PR DESCRIPTION
**Pull request by mmarkelov**
close #191 #194 and perhaps #144

### CODE REVIEW

**Comment by mxschmitt** [comment]
lgtm, but we probably have to add playwright-core as a dev dependency since its not installed by default anymore.

**Comment by mmarkelov** [comment]
> we probably have to add playwright-core as a dev dependency

maybe you are talking about to add it to **dependencies**?

**Comment by mxschmitt** [comment]
> > we probably have to add playwright-core as a dev dependency
> 
> @mxschmitt maybe you are talking about to add it to **dependencies**?

yep, sorry! I mean dependencies 👍  So that playwright-core will be installed with our package.

**Comment by mmarkelov** [comment]
@mxschmitt got it and move it =)

**Comment by mmarkelov** [comment]
Also fix a bug from #203, cause when we are passing `connectOptions` they are ignored
https://github.com/playwright-community/jest-playwright/blob/0e7228dbc048aee6ab577b5cce27f35144766a51/src/PlaywrightEnvironment.ts#L86-L91

**Comment by mmarkelov** [comment]
@mxschmitt seems like that there is a problem with github actions

**Pull request merged**
