### PR TITLE
feat: create browser context and page per test

### PR DESCRIPTION
**Pull request by dgozman**
What do you think about this major breaking change?

Pros:
- Ensures isolation between tests and therefore guards against subtle inter-dependencies between tests making everything flaky over time.

Cons:
- Breaking change. Existing test suites which rely on a single page will break.
- Large test suites that used to do a lot of small tests will be slower, because they have to create page multiple times. With context per test, the better strategy would be to include multiple checks  into a single test, when they are related to a single scenario.

We can also add a helper for new context (encapsulating context options), or expose context options, to allow users to manually reuse page between tests if they really need to:

```js
let context;
let page;

beforeAll(async () => {
  // exposing newContext
  context = await global.newContext();
  // or exposing contextOptions
  context = await global.browser.newContext(global.contextOptions);
  page = await context.newPage();
});

afterAll(async () => {
  await context.close();
});
```

Note: I am not sure this is a best way to integrate "context per test" with jest ecosystem, any advice is appreciated.

### CODE REVIEW

**Comment by mxschmitt** [comment]
great idea, I really like the way how you want to encapsulate the context sessions per `it()` statement. But I would make it configurable, because maybe most of the users want to have at least a shared page instance between a `describe()` statement (or file I guess, thats how we are currently handling it) to just login to a page a single time at the top.

So maybe we could add `encapsulationMode` or something like that to the `jest-plawright.config.js` to set it either to `it` or `file` so that the user can decide in the end.

What do you think about that approach?

Or maybe I'm totally wrong and each `it()` statement should be 100% independed and contain a own login in the end, not sure what the best practises for that are.

**Comment by celeryclub** [comment]
This is an interesting idea. I want to dig into the initial assumption a bit though - that interdependencies within a spec file cause flakiness over time. In my experience what makes tests flaky is not having enough knowledge about the state of your app under test and what reliably signifies a "ready" state.

If we move in this direction, we'll be encouraging people to write very large `test` blocks, since often a particular test does require a substantial amount of state built up before running any assertions, and using a single `test` block loses the granularity in logging that smaller blocks give you. Granted, there may be another way to achieve this granularity, but I think end-to-end tests are kind of a different animal from unit tests and I wonder if making each `test` block truly independent is really necessary.

If you think I'm way off base feel free to say so. :)

**Comment by dgozman** [comment]
Overall, we feel pretty strongly about tests being isolated and each one creating a new browser context. This allows parallelization without side effects to significantly speed up test runs, reduces flakiness and helps with tooling (e.g. re-running tests, dashboards, predictable isolation to reproduce/debug failures, etc.). We hope that existing users of Playwright will share the same mindset 😄

Let me address some of the concerns separately:

> to just login to a page a single time at the top

A possible solution is to login once in `beforeAll()`, save cookies from the browser context, and restore them in each test as a first line or in `beforeEach()`. If there is something else missing, we are happy to help!

> I want to dig into the initial assumption a bit though - that interdependencies within a spec file cause flakiness over time

Basically, if one of the earlier tests fails or introduces some flakiness, later tests are mostly useless. Most likely, they won't pass either, or even if they do it might not indicate that application actually works as intended.

> using a single test block loses the granularity in logging that smaller blocks give you

That's an interesting point. We'd like to help with this if possible. Mind sharing an example when you stumble upon one? My assumption is that logs after the first failure are mostly noise - it is somewhat similar to C++ compiler errors where only the first one is definitely an error, and the rest depends on your luck.

> since often a particular test does require a substantial amount of state built up before running any assertions

The typical solution is to extract helpers like `addItemAndShowDetails(page, item)`. Page object model is a quite popular technique in this area.

> not having enough knowledge about the state of your app under test and what reliably signifies a "ready" state

This is indeed a big issue, which we are actively looking at. Please share your experience and scenarios so that we can help. I think it is an issue in any test setup though 😄

**Comment by mxschmitt** [comment]
Closed since we (including @dgozman) will come up in a few weeks with a better solution to handle that by a reworked version.

**Pull request closed without merging**
